par(mfrow = c(2,2))
with(plot_data, plot(time, Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = ""))
with(plot_data, plot(time, Voltage, type = "l", xlab = "datetime", ylab = "Voltage"))
with(plot_data, plot(time, Sub_metering_1, type = "l", col = "black", ylab = "Energy sub metering", xlab = ""))
with(plot_data, lines(time, Sub_metering_2, col = "red"))
with(plot_data, lines(time, Sub_metering_3, col = "blue"))
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5)
with(plot_data, plot(time, Global_reactive_power, type = "l", xlab = "datetime"))
dev.copy(png, width = 480, height = 480, file = "plot4.png")
dev.off()
