with(plot_data, plot(time, Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering"))
with(plot_data, lines(time, Sub_metering_2, col = "red"))
with(plot_data, lines(time, Sub_metering_3, col = "blue"))
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, width = 480, height = 480, file = "plot3.png")
dev.off()
